# mezora theme - sauce for macchina cli

separator=""
separator_color="blue"
key_color="blue"
prefer_small_ascii = true

[palette]
type="Dark"
visible=true
glyph=" ⬤ "

[box]
title=" yjydist "
# border="double"
visible=true

[bar]
glyph=""
hide_delimiters=true
visible=true

[randomize]
key_color=false
separator_color=false

[custom_ascii]
color="blue"
visible=false

[keys]
host="host"
kernel="kernel"
distro="os"
packages="packages"
terminal="terminal"
shell="shell"
cpu="cpu"
cpu_load="cpu_load"
memory="memory"
battery="battery"
